# FormLicense by poikcue.
# Active Version: 1.13-1.18.1 (NOT TESTED BETWEEN 1.14 AND 1.17)
# Report bug: Submit an issue at github.com/poikcue/FormLicense
# Version:1.3.1-BETA-2
# WARN: YOU ARE USING BETA VERSION! PLEASE BACK UP!
FormLicense:
  HideDevelopmentVersionWarning: false
  # FormLicense development version warning
  # This version is alpha,beta or development version.* NOT A OFFICIAL VERSION! *
  # This means that the version is untested or (possibly) still have bug.
  # If you modify the plugin and test it yourself, there should be no problem.
  # If you have any problems with the development version, please submit an issue in GitHub and stop using it immediately. The developer will not bear * any * responsibility for this.
  # If you want to hide this information, set config.yml 'formlicense 'developmentversion' to false
PlayerNoLicenseAllow:
  pickup: true
  UsePortal: true
  hit:
    hit: true
    be-hit: true
  target: true
Message:
  action-bar-message: "I'm sorry but you don't have license.Please type &a/license &fto check."
  hit-message:
    hit-action-bar-message: "You don't have license!Damage has been cancelled."
    be-hit-action-bar-message: "You can't hit them!"
  no-license-player-join-message: "You don't have license.Some function locked."
  command-with-license: "You don't have license!"
  command-with-no-license: "You have license!"
  reload-with-permission: "Successful reload!"
  reload-with-no-permission: "You can't do this!"