name: FormLicense
main: poikcue.form.license.FormLicense
version: 1.3.1
api-version: 1.13
commands:
  license:
    aliases:
      - "lic"
      - "licenses"
    usage: "/license"
    description: "Allow player to check them license."
  licensereload:
    aliases:
      - "licreload"
      - "reloadlicense"
    usage: "/licensereload"
    description: "Allow people to reload license system"
